### ISSUE TITLE
Confusing changes in artifactory for maven cache

### ISSUE THREAD

**Issue by jamshid** [JFrogDev/artifactory-docker-examples#1]
Hi, I've been using jfrog-docker-reg2.bintray.io/jfrog/artifactory-oss:latest as my maven cache server. Either it changed recently or maybe docker 1.13 broke it, so I tried resetting the environment.

The new artifactory instructions and images are really confusing. This is supposedly "Running with Docker for V4.x":

https://www.jfrog.com/confluence/display/RTF/Running+Artifactory+OSS

but it says to use `docker pull docker.bintray.io/jfrog/artifactory-oss:latest` but that is the latest 5.0, not 4.x. Should it be `frog-docker-reg2.bintray.io/jfrog/artifactory-oss:4.1.0` instead? Or `docker.bintray.io/jfrog/artifactory-oss:4.1.2`?

And does 5.0 really require an interactive setup in order to enable the maven repository? That used to be automatic, is there any way to script that to use default installation options?

**Comment by eldada** [comment]
About the versions confusion - you are right. The Wiki was still using the `:latest` for the image tags. It's fixed now to show `:4.16.0`. We use the same registry and tag, so you have to specify the version 4 family if not planning on using version 5 (`:latest`).
You should use the `docker.bintray.io` tag. It's simply an alias to `frog-docker-reg2.bintray.io`, so you can't go wrong.

As for the initial setup - we'll fix it with an ability to pre-define the setup and load it to a new instance so it will allow you to set initial configurations such as the default repositories to create. This ability already exists in the Artifactory Pro release.
The fix will be released in the coming weeks.

**Comment by jamshid** [comment]
Thanks okay that makes sense. 

Btw I'm having a problem with the docker.bintray.io/jfrog/artifactory-oss:4.16.0 java process sometimes disappearing, I think due to Docker for Mac being under heavy load. I don't see any heapdump output on the file system (.hprof?), so maybe docker itself is killing `java`? 

When this happens /tmp/run.sh is still running, I guess `/etc/init.d/artifactory wait` doesn't exit when java process gets killed.

Just wondering if you've seen this or know how get debug logging? Editing below config files doesn't help, I'm only seeing INFO logs in artifactory.log
```
sed --in-place 's/INFO/DEBUG/g' /opt/jfrog/artifactory/tomcat/conf/logging.properties 
sed --in-place -e 's/info/debug/g' -e 's/debug=.false./debug=\"true\"/' /var/opt/jfrog/artifactory/defaults/etc/logback.xml
```

**Comment by matankatz** [comment]
`/etc/init.d/artifactory wait`is built out of two commands, `artifactory start && tail -f /var/opt/jfrog/artifactory/logs/artifactory.log`.
Therefore if for some reason java process is being killed, run.sh is still running.

The correct `logback.xml` file to edit is in `/var/opt/jfrog/artifactory/etc/logback.xml` and changing "info" level to "debug" will be enough.

To determine what is the reason for the java process being killed we need to look both in Artifactory logs and tomcat's Catalina logs.

In 4.11.1 we added flag to the JVM causing Artifactory to stop in case of out of memory problem.
https://www.jfrog.com/jira/browse/RTFACT-8735.

If this is indeed the case, you can start Artifactory with larger heap size than the default which is 2GB using `-e RUNTIME_OPTS=-Xmx4g`.

**Comment by eldada** [comment]
@jamshid - I wanted to let you know that you can now automate the automatic repositories setup at Artifactory OSS first boot by using the instructions in https://www.jfrog.com/confluence/display/RTF/Getting+Started#GettingStarted-YAMLConfigurationFile
The only thing is that you need to set an empty `licenseKey: ""`, since it's OSS.
Uncomment the `- maven` in `repoTypes` (and any other you want to auto create).

I think we covered all your questions in this issue. Closing. Let us know if you think otherwise.
