### ISSUE TITLE
Why mounting postgresql.jar is required?

### ISSUE THREAD

**Issue by andreychernih** [JFrogDev/artifactory-docker-examples#14]
This is the manual step which requires human intervention to get Artifactory up and running. Why not to vendor it in inside the container?

**Comment by eldada** [comment]
@andreychernih - good point!
Few issues to point out.
- Artifactory support many database types, so we don't want to tie to any particular brand
- There are legal implications for distributing open source 3rd party with your commercial software. Must be aware of it. See [discussion here](http://softwareengineering.stackexchange.com/questions/47032/can-i-use-gpl-software-in-a-commercial-application)
- You can build your own version of an Artifactory Docker image with an already driver injected into it. See the Dockerfiles in our [Kubernetes examples](https://github.com/JFrogDev/artifactory-docker-examples/tree/master/kubernetes). Host it on your own repository and update the compose yaml to take it without a need to mount it.

Let me know if this answers your question, so I can close this issue.

**Comment by andreychernih** [comment]
I guess your point about legal issues covers my question fully :) This totally makes sense, thank you.

**Comment by eldada** [comment]
@andreychernih - I'm happy to tell you that starting next version, we'll release Artifactory Pro docker image pre-loaded with the PostgreSQL driver (we are OK on the legal side here).
Watch out for our next release coming soon!
