### ISSUE TITLE
Swarm Mode Version?

### ISSUE THREAD

**Issue by ghost** [JFrogDev/artifactory-docker-examples#23]
Requesting swarm mode (v3 file) Artifactory as a Docker Service version.

**Comment by eldada** [comment]
@tim-wilcoxson - We'll look into it. You are also welcome to contribute here :-)

**Comment by tim-wilcoxson** [comment]
@eldada - I'm going to convert one of the compose files you all provided and if it's sensical I'll contribute.  Either way, being new to Artifactory, it's nice to see how you all would do it.  Thanks!!

**Comment by mfuxi** [comment]
I was trying to create a service in docker swarm in order to test Artifactory on Swarm and failed to do so using this command:
`docker service create --replicas 1 --name artifactory --network tstNet -p 8081:8081 docker.bintray.io/jfrog/artifactory-pro`

and got this error:
> unable to pin image docker.bintray.io/jfrog/artifactory-pro to digest: missing or empty Content-Length header

any idea how to solve this issue?

**Comment by eldada** [comment]
@mfuxi - What about just setting the explicit version `docker.bintray.io/jfrog/artifactory-pro:5.4.1`.
Does this resolve it?

**Comment by mfuxi** [comment]
@eldada I tried that as well, but got the same error message
Have you managed to run swarm mode with Artifactory?

**Comment by eldada** [comment]
@mfuxi - I haven't tried SWARM with compose v3. I got it working in the past with v2.
I will consult my team here and get back to you.

**Comment by mfuxi** [comment]
@eldada I'm not even using compose, just tried for starters to create the service without docker-compose..
Of course later on I will use docker-compose to run my instance in the right manner.

**Comment by eldada** [comment]
@mfuxi - Can you help me reproduce?
- What is your SWARM setup? Version, installation type and environment.
- What are the commands used to all they way up to your `docker service create` execution?

**Comment by mfuxi** [comment]
@eldada 

-  Docker version 17.03.1-ce, build c6d412e, what do you mean by installation and environment? i'm using it on an Azure Ubuntu 16.04.2 machine

- The simplest commands: `docker swarm init \` 
`docker service create --replicas 1 --name artifactory -p 80:8081 docker.bintray.io/jfrog/artifactory-pro@sha256:91405d6761f943739f5041808826eec5f88cbffc094b74ed72a4fc48c83521b0
`

That's it.

**Comment by mfuxi** [comment]
@eldada I had managed to run Artifactory services (postgresql, nginx and artifactory) on SWARM using **artifactory-pro.yml**, I changed and added some of the properties:
added to each of the services: 
`deploy:`
      `mode: replicated`
      `replicas: 1`
And changed to each of the services from: `docker.bintray.io/jfrog/artifactory-pro:5.4.0` to `docker.bintray.io/jfrog/artifactory-pro:latest`

and also from `Version: '2'` to `Version: '3'`

I'm running the yml file using these commands: 
`docker swarm init`
`docker stack deploy -c artifactory-pro.yml artifactory`

Is this a best practice, would you like me to share this code?

**Comment by eldada** [comment]
@mfuxi - I happy you got it working!
I'm all for sharing. Do you want to submit a formal pull request?
- Need to set an explicit version (currently 5.4.1 is latest)
- Provide a readme with 
    - Links to instructions on setting up swarm (no need to detail it here)
    - Instructions on spinning up Artifactory in swarm using the compose example you provide

Since this is a new orchestrator, I want to see it in a new top level directory of it's own `swarm`.
Let me know how you want to proceed.

**Comment by mfuxi** [comment]
@eldada Yeah sure I will submit a format pull request with all the needed code and documentation.

**Comment by eldada** [comment]
We now have a Swarm example using a compose yaml.
