### ISSUE TITLE
Problem - download images from docker.bintray.io

### ISSUE THREAD

**Issue by JarRoDk** [JFrogDev/artifactory-docker-examples#24]
Hi i have problem to download images. 
Yesterday (13.06.2017) it works. I am trying to use https://github.com/JFrogDev/artifactory-docker-examples/blob/master/docker-compose/artifactory-pro.yml

docker.bintray.io/postgres:9.5.2
docker.bintray.io/jfrog/artifactory-pro:5.3.2
docker.bintray.io/jfrog/nginx-artifactory-pro:5.3.2

**Comment by eldada** [comment]
Hi @JarRoDk ,
I just checked a `pull` on a public network and it works
```
16:25 $ docker pull docker.bintray.io/jfrog/artifactory-pro:5.3.2
5.3.2: Pulling from jfrog/artifactory-pro
43c265008fae: Already exists 
af36d2c7a148: Already exists 
143e9d501644: Already exists 
bfc4cdbc8d81: Already exists 
38c6fc3e9968: Already exists 
0bfa8d5153bb: Already exists 
05bc8d0fffca: Already exists 
f1266a2a7ecb: Already exists 
55154431b279: Downloading [====================================>              ] 64.21 MB/87.41 MB
7e68651520ff: Download complete 
37ce5c92c25a: Download complete 
3a8dcf30dc42: Downloading [============================================>      ] 74.71 MB/83.14 MB
1ee56eb783e6: Downloading [==========================>                        ] 46.68 MB/87.37 MB
ae9d0331e30f: Waiting 
```

I assume something changed in your network settings.

Eldad

**Comment by JarRoDk** [comment]
Ok, thx to confirm.

**Comment by paulcayon** [comment]
Hello,

I have the same problem actually with the OSS version :

https://github.com/JFrogDev/artifactory-docker-examples/blob/master/docker-compose/artifactory-oss-postgresql.yml

```
artifactory git:(master) ✗ docker-compose up
Pulling artifactory (docker.bintray.io/jfrog/artifactory-oss:5.4.2)...
5.4.2: Pulling from jfrog/artifactory-oss
43c265008fae: Already exists
af36d2c7a148: Already exists
143e9d501644: Already exists
c933b00c3409: Already exists
b2df646b60f9: Already exists
ceeb7ccd5b89: Already exists
05bc8d0fffca: Waiting

```

I copy the content of the artifactory-oss-postgresql.yml to a docker-compose.yml file (this is why I can use docker-compose up without -f option)

any Idea ?

**Comment by eldada** [comment]
@paulcayon - I tested it now, and the `pull` is ok now. You might have experienced temporary network hangs.
Can you test again and confirm it's working?
