### ISSUE TITLE
Amazon Linux wont start with compose due to ulimit

### ISSUE THREAD

**Issue by johnrkriter** [JFrogDev/artifactory-docker-examples#26]
Currently, I have had issues starting the artifactory-pro-nginx-derby.yml compose file due to limits within amazon linux. The issue is that the containers inherit a very small ulimit(1024) no matter what I do.

What I suggest is to add a ulimit configuration to the docker compose files.
Something like    
ulimits:
        nproc: 65535
        nofile:
            soft: 20000
            hard: 40000

**Comment by eldada** [comment]
Thx @johnrkriter for this. Did you see the errors in the Artifactory log (it's supposed to warn or fail if limits are not good)?

**Comment by johnrkriter** [comment]
Yes it warned me that the ulimit was 1024 and was too low, so it stopped the start up.

John Kriter
[cid:image001.png@01D2F036.B683B1F0]
Technology Architect
Lync / E-mail : John.R.Kriter@Accenture.com<mailto:John.R.Kriter@Accenture.com>
Phone US: 713-982-7962
Phone International: 832-305-1567

**Comment by eldada** [comment]
Hi @johnrkriter. Thanks for this. Do you want to issue a formal pull request with this improvement? We encourage contributions!

**Comment by johnrkriter** [comment]
PR opened referencing issue #26

________________________________
