### ISSUE TITLE
Suggested Volume for Deployment using Swarm in AWS

### ISSUE THREAD

**Issue by marcellodesales** [JFrogDev/artifactory-docker-examples#33]
Hi there,

Requirements
----

* Our enterprise has apps that requires the most popular Registries such as Docker, Java, NPM, YUM (RPM), etc.
 * We are a RHEL shop
* We need to support more than a thousand users around the globe
 * Comes down to thousands of Builds servers (AMI, Packer, Jenkins, CircleCI, etc)
* We need a centralized, HA solution for all
* We got a PRO license and our enterprise might be discussing long-term licenses.

Volume Requirement - Swarm Mode - Questions
-----

* Taking into account https://github.com/JFrogDev/artifactory-docker-examples/tree/master/swarm
* Given the requirements above, what Volume management do you think it is feasible to use? 
* I've been experimenting with RexRay for Volume management backed by `AWS EBS` (single Host) and not started with `AWS EFS` (HA) for other applications. 

Questions:

* What is the appropriate architecture for dealing with remote Volume in an HA environment?
 * What volume in AWS? EFS? EBS? S3?
 * Any Trade-offs info around those?
* When deploying everything using Swarm Mode, what is your recommended approach for each of the separate Registries needed?
* Should a single install be sufficient for all the requirement, or should we partition installations in different accounts/regions? 

thank you!

**Comment by eldada** [comment]
Hi @marcellodesales ,
Your query has a lot of issues to cover. Some are out of this repository's scope. I'll try and give you some answers and directions 😄 
- It looks like you require an HA setup. Artifactory excels at that. The Docker based solutions can provide you that. This repository has a few options as examples.
- For storage, there are many options for artifactory. Especially if you install on a public cloud like AWS. See options plus examples at https://www.jfrog.com/confluence/display/RTF/Configuring+the+Filestore. It's hard to recommend a single option as they all have their prods and cons. 
- Most of the issues here are out of the scope of this repository. You should go to https://support.jfrog.com/ to get more details and ask for specific support.

I hope this gives you an initial path to follow.

**Comment by marcellodesales** [comment]
Thanks a lot @eldada... We will go through the support channel for more info!

**Comment by vamsi248** [comment]
below are my logs like this....

Starting artifactory...
Found java executable in JAVA_HOME (/docker-java-home/jre)
mkdir: cannot create directory ‘/opt/artifactory/logs/catalina’: Permission denied

** Could not create dir /opt/artifactory/logs/catalina

once i deleted the user lines in the docker then it has taken the root user and container running fine..
why its not giving permission to create that directory in the artifactory user..... any idea...

i need to add anything extra in my dockerfile....

FROM openjdk:8-jre

MAINTAINER xxxxxxxxxxx>

Define environment variables

ENV ARTIFACTORY_HOME=/opt/artifactory
ENV ARTIFACTORY_VERSION=5.4.6
ENV MIN_HEAP_SIZE="-Xms512m"
ENV MAX_HEAP_SIZE="-Xmx2g"

Create artifactory group and user 

RUN groupadd -g 1000 artifactory 
&& useradd -d "$ARTIFACTORY_HOME" -u 1000 -g 1000 -s /sbin/nologin artifactory

Install artifactory

RUN wget "https://api.bintray.com/content/jfrog/artifactory/jfrog-artifactory-oss-${ARTIFACTORY_VERSION}.zip;bt_package=jfrog-artifactory-oss-zip" && 
unzip "jfrog-artifactory-oss-${ARTIFACTORY_VERSION}.zip;bt_package=jfrog-artifactory-oss-zip" && 
mv artifactory-oss-${ARTIFACTORY_VERSION} $ARTIFACTORY_HOME && 
rm "jfrog-artifactory-oss-${ARTIFACTORY_VERSION}.zip;bt_package=jfrog-artifactory-oss-zip"

Define mountable directories

VOLUME $ARTIFACTORY_HOME/data
VOLUME $ARTIFACTORY_HOME/etc
VOLUME $ARTIFACTORY_HOME/logs
VOLUME $ARTIFACTORY_HOME/backup
VOLUME $ARTIFACTORY_HOME/access

Add initialization script

ADD entrypoint.sh /opt/artifactory/bin/entrypoint.sh

Modify script permissions

RUN chmod 755 /opt/artifactory/bin/entrypoint.sh

Change directories ownership to artifactory user and group 

RUN chown -R artifactory:artifactory $ARTIFACTORY_HOME

Run the container as artifactory user 

USER artifactory

Define default command

ENTRYPOINT ["/opt/artifactory/bin/entrypoint.sh"]

Expose port

EXPOSE 8081

**Comment by vamsi248** [comment]
can anyone help me in this issue @marcellodesales @whiteley @jfrog
