### ISSUE TITLE
Artifactory in docker swarm does not work

### ISSUE THREAD

**Issue by NasAmin** [JFrogDev/artifactory-docker-examples#36]
Hi,

We are using Artifactory enterprise license and trying to setup a multi site network topology. Is Docker swarm mode suitable for that?

Volumes don't work in docker  swarm-mode
Container names aren't supported
Unable to manage artifactory instances and the Swarm's load balancer will take to any task running the instance and not the one you want to manage in Mission Control.
Is Swarm Mode appropriate for multi site topology?

**Comment by marcellodesales** [comment]
HI @NasAmin 

I'm working towards the following architecture...

* Use RexRay Docker volume plugin for EBS to store the Database Data
 * Single Container can Write to the FS
* Use RexRay Docker volume plugin for EFS to store the Web App Data
 * Multiple Containers can write to the FS

Finally got Docker Volumes to work in AWS https://github.com/codedellemc/rexray/issues/820#issuecomment-323624765. I haven't had time to work on it, but our team has worked in deploying the multi-site statically without Docker, but I wanna take this opportunity to do it Dockerized in Swarm...

The work I'm planning is based on a Workshop at Dockercon where the presenter Dockerized his infrastructure entirely in Swarm, including the Docker Registry using Docker Volumes in Swam...

**Comment by eldada** [comment]
@NasAmin , @marcellodesales - guys - this is old. Is it still relevant? Or can I close it?

**Comment by NasAmin** [comment]
Yes you may close this issue. What I am trying to do isn't easily possible with Swarm-mode
