### ISSUE TITLE
Artifactory Docker Image(s) should support secrets

### ISSUE THREAD

**Issue by holgerstolzenberg** [JFrogDev/artifactory-docker-examples#37]
Currently, if using an external database, an environment property for setting the database password can be leveraged.

A better way would be to use Docker secrets. The official PostgreSQL image show cases how that can be achieved. They leave the choice to the user to provide the password via env property or secret definition.

More details can be found here: https://github.com/docker-library/postgres/issues/111

(I am not quite sure if this is the correct place to report the issue. If not please correct me.)

**Comment by eldada** [comment]
Hi @holgerstolzenberg . This is a good idea. You can open a task in https://www.jfrog.com/jira/secure/Dashboard.jspa.

**Comment by holgerstolzenberg** [comment]
JIRA issue was created:
https://www.jfrog.com/jira/browse/RTFACT-14826

**Comment by eldada** [comment]
Great! I will close this and allow Artifactory dev to take the JIRA issue.
