### ISSUE TITLE
The nginx proxy pass value is not changing to the value of art_base_url in the docker compose file.

### ISSUE THREAD

**Issue by jinro79** [JFrogDev/artifactory-docker-examples#38]
Maybe I'm doing this wrong, I set ART_BASE_URL=http://mycustomartifactory:8081/artifactory in my docker compose file.  When I start with "docker-compose up " the nginx proxy pass does not change to the value in ART__BASE_URL.  It is still http://artifactory:8081/artifactory.  I have to stop the containers, change the file manually and then restart the containers to get it to work.

Thanks

**Comment by eldada** [comment]
Hi @jinro79  - this is a good catch.
Can you add it to the main [Artifactory JIRA](https://www.jfrog.com/jira/projects/RTFACT/)? It should be checked and fixed there.

(sorry for the late reply)

Closing here.

**Comment by markeijsermans** [comment]
Somewhat related: the source for the nginx container (`docker.bintray.io/jfrog/nginx-artifactory-pro:5.5.1`) is missing so the `/entrypoint-nginx.sh` can't be fixed here
