### ISSUE TITLE
Securing Artifactory with SSL

### ISSUE THREAD

**Issue by holgerstolzenberg** [JFrogDev/artifactory-docker-examples#40]
Is there any option to secure the `docker.bintray.io/jfrog/artifactory-oss` image directly with SSL?

Currently I only found examples that use the opinionated `nginx-artifactory-pro` image what yields some problems:

Imagine a Swarm cluster that provides some CI services like Artifactory, Jenkins and so on. Having all these services inside the swarm, often one central API/reverse proxy is desired (like Traefik) so that traffic can be routed to the distinct services **without having to bring up a dedicated poxy for each service**.

Also, having multiple proxies running in the swarm but port 443 being only bindable once, so kind of port mapping needs to be done in front of the Swarm cluster what is also no real good.

There is also a security concern, as traffic between Artifactory and the reverse proxy itself is not encrypted.

**Comment by eldada** [comment]
@holgerstolzenberg - you can use the `docker.bintray.io/jfrog/nginx-artifactory-pro` or any standard `nginx` image to provide you with the SSL.
You can add Artifactory OSS to your existing load balancer in a cluster of services.
If you insist, you can build a new Docker image that has Artifactory and Nginx together (not recommended) to avoid having them talk on the host network, although I think this is an overkill.

I hope this gives you an idea...

**Comment by holgerstolzenberg** [comment]
Thanks for the answer, but the idea is already clear. In our scenario we use traefik.io to reverse proxy services within a Swarm cluster. One of these services is Artifactory. It works without any problems. The problematic point is that SSL is terminated at the Traefik reverse proxy, but communication between Traefik <-> Artifactory is still unencrypted.

Using `docker.bintray.io/jfrog/nginx-artifactory-pro` will not solve the problem, as communication between the Nginx <-> Artifactory will be unencrypted.

I know that overlay networks can be encrypted. Looking at https://docs.docker.com/engine/userguide/networking/overlay-security-model/ you can see that:

> You can also encrypt data exchanged between containers on different nodes on the overlay network.

In my understanding, in a hypothetic situation, having Nginx/Traefik and Artifactory running on the same host, communication between them is unencrypted and might be sniffed.

For me, an possible solution could be to be able to enable the SSL connector of the Tomcat via env properties (and disable HTTP connector likewise).

I do not know the deeper architecture of Artifactory. Looking at it from a wider perspective entering the container world, it looks like migrating Artifactory to a standalone app with a SSL secured embedded servlet container is a reasonable choice (Spring Boot).

**Comment by eldada** [comment]
Look at https://www.jfrog.com/jira/browse/RTFACT-7201. I think this is what you are looking for, but it will require you to build a new Docker image based on `docker.bintray.io/jfrog/artifactory-oss` that does the needed modifications to `server.xml`.
I'm closing this issue. Feel free to open a JIRA issue if you think more is required.
