### ISSUE TITLE
Dockerfile available?

### ISSUE THREAD

**Issue by katzefudder** [JFrogDev/artifactory-docker-examples#41]
I'm currently trying to find a Dockerfile for docker.bintray.io/jfrog/artifactory-pro.
Is there one available somewhere?

**Comment by eldada** [comment]
Hi @katzefudder - you can find the OSS Docker file in the Artifactory OSS sources: https://jfrog.bintray.com/artifactory/jfrog-artifactory-oss-5.5.1-sources.tar.gz

There is a `distribution/docker` module. It has the sources for the Docker image. It's almost identical to the Pro version.

If you want more specific details, look at https://bintray.com/jfrog/reg2/jfrog%3Aartifactory-pro. It has a graphic outlining of the image (scroll to the `Docker Details` section).


We have future plans to add the *Dockerfiles* for Artifactory OSS/PRO and the needed resources to this repo in the future.

**Comment by katzefudder** [comment]
You're doing many things with the _entrypoint-artifactory.sh_, which unfortunately differs between OSS and  PRO. I'm pretty interested in having all parts in this repo, as it would make setup via Docker a lot more obvious and would also make documentation a lot more comprehensive than it is today.

**Comment by eldada** [comment]
Go ahead and pull the `docker.bintray.io/jfrog/artifactory-pro:5.5.1` image, and `bash` into it
```
docker run --rm -it --entrypoint=/bin/bash docker.bintray.io/jfrog/artifactory-pro:5.5.1
```
Then, you can see `/entrypoint-artifactory.sh`.

**Comment by katzefudder** [comment]
Well, sure, I know that... somehow, I had the chance to look at it before I was reaching out to you ;)
We're actually trying to run Artifactory in production, and are currently evaluating different approaches about how we deploy the software in AWS. Having all the sources (all the glue that puts Artifactory in place) at hand would be a nice thing to have, even when thinking about maintainance and future releases.
