### ISSUE TITLE
Unable to access artifactory gui when running artifactory container on nfs mounted volume

### ISSUE THREAD

**Issue by jinro79** [JFrogDev/artifactory-docker-examples#48]
I can run artifactory-nginx-postgres just fine with the docker compose file provided. 

I add the fstab entry and mount /data/artifactory to an nfs share, I can no longer reach the artifactory web gui.  I check the logs and it looks like everything has started correctly, but I get a HTTP Status 404 - not found error. NFS versions 3 and 4 have been tried with the same result.

I unmount the share, restart docker-compose and everything is working again.

**Comment by eldada** [comment]
Does artifactory user/process have write permissions to the mounted volume?

**Comment by jinro79** [comment]
I was able to resolve this issue on my own but didn't have a chance to update.  The owner and group of the plugins folder and it's contents was not artifactory:artifactory.  Chown to artifactory:artifactory and restart got things working on the nfs share.  I'll add the exact path that was the issue when I get back to the office tomorrow.  You can mark this resolved.

**Comment by jinro79** [comment]
eldada thanks for support!
