### ISSUE TITLE
Docker image file permissions

### ISSUE THREAD

**Issue by ju2wheels** [JFrogDev/artifactory-docker-examples#58]
I have been using the following Artifactory Docker images:

|Image|Volume|
|--------|----------|
|docker.bintray.io/jfrog/artifactory-pro:5.9.0|`/srv/artifactory/artifactory:/var/opt/jfrog/artifactory`|
|docker.bintray.io/jfrog/nginx-artifactory-pro:5.9.0|`/srv/artifactory/nginx:/var/opt/jfrog/nginx`|

I am using configuration management to place files into `/srv/artifactory/artifactory` aka my `ARTIFACTORY_HOME` and `/srv/artifactory/nginx` for the Nginx config and SSL files.

The problem I am running into with this is that both Docker images do not recursively chown all the contents of their respective folders to the right user/group on startup before starting the main Artifactory/nginx daemon.

What this means is if my configuration management on my host system sets the owner/group on the files to root:root, when we start the Artifactory image, it thinks some files are not there simply because it doesnt have ownership rights to them and fails to start properly.

What makes this more confusing to manage is that looking at the uid/gid assigned to these files on the host makes no sense from outside of the containers themselves because it can be a uid/gid that exists only in the container or random user/group on the host based on whatever uid/gid matches.

This is a request to make these containers always recursively chown the files in these folders to the respective uid/gid of each service before starting it so we dont have to manage this from outside the container in whatever volumes we use.

**Comment by eldada** [comment]
Hi @ju2wheels - `chowning` a directory in a Docker container might be a problem. It requires you to be **root** when running the entrypoint.
If you look at the artifactory entrypoint - `/entrypoint-artifactory.sh`, you will see we already have a `chown` (calling function in line 237). But - we are planning on removing this in a future release.
There is a requirement to avoid running the container as **root** altogether. Even if the artifactory process is running as artifactory user.
This means your automation will have to prepare the volumes permissions before starting Docker. The default artifactory user id is 1030, and you can override it.
Also, you can create your own Docker images based on 
```
docker.bintray.io/jfrog/artifactory-pro:5.9.0
docker.bintray.io/jfrog/nginx-artifactory-pro:5.9.0
```
Where you can override the entrypoint and prepare the storage as you want it.

**Comment by ju2wheels** [comment]
OK, closing.

Thanks,
