### ISSUE TITLE
Settting JAVA Max Memory

### ISSUE THREAD

**Issue by Idanatcox** [JFrogDev/artifactory-docker-examples#63]
When setting "EXTRA_JAVA_OPTIONS=-Xmx8g" the JVM will launch with with duplicate "-Xmx" args

**JVM Arguments:**
Args:  -Djava.util.logging.config.file=/opt/jfrog/artifactory/tomcat/conf/logging.properties
-Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
-Djdk.tls.ephemeralDHKeySize=****
-Djava.protocol.handler.pkgs=org.apache.catalina.webresources
-Xms512m
**-Xmx2g**
-Xss256k
-XX:+UseG1GC
-XX:OnOutOfMemoryError=kill -9 %p
-Djruby.compile.invokedynamic=false
-Dfile.encoding=UTF8
-Dartdist=zip
-Dorg.apache.tomcat.util.buf.UDecoder.ALLOW_ENCODED_SLASH=true
-Djava.security.egd=file:/dev/./urandom
**-Xmx8g**

**Comment by eldada** [comment]
Hi @Idanatcox . You are right. This is very common in customising Java applications.
You start with a default set of parameters, and add your custom ones to the end of the JVM parameter list. This might result in duplication of parameters.
The JVM knows to use the latter occurrence of every parameter. This might look ugly, but it works well.
In your case, only **-Xmx8g** will be used.

**Comment by Idanatcox** [comment]
Thanks, I've tested it and it works correctly.
