### ISSUE TITLE
Helm charts fail lint

### ISSUE THREAD

**Issue by maguro** [JFrogDev/artifactory-docker-examples#67]
$ helm lint --strict artifactory-ha
    ==> Linting artifactory-ha
    [ERROR] templates/: render error in "artifactory-ha/templates/nginx-service.yaml": template: artifactory-ha/templates/_helpers.tpl:54:14: executing "artifactory-ha.nginx.fullname" at <.Values.nginx.fullna...>: map has no entry for key "fullnameOverride"
    
    Error: 1 chart(s) linted, 1 chart(s) failed
    $ helm lint --strict artifactory
    ==> Linting artifactory
    [ERROR] templates/: render error in "artifactory/templates/nginx-service.yaml": template: artifactory/templates/_helpers.tpl:30:40: executing "artifactory.nginx.fullname" at <.Values.nameOverride>: map has no entry for key "nameOverride"
    
    Error: 1 chart(s) linted, 1 chart(s) failed

**Comment by eldada** [comment]
Hi @maguro . The official helm charts repository and the best practices use `helm lint` only. Without the `--strict` flag, so we follow similar.
Passing the `--strict` check will require us to put almost all of the sub-chart parameters in the main **values.yaml**, which I'd like to avoid so to reduce complexity.

**Comment by maguro** [comment]
Makes sense to me.
