### ISSUE TITLE
Small typo creates a problem

### ISSUE THREAD

**Issue by 0pen5pace** [JFrogDev/artifactory-docker-examples#77]
The template should be defined as following 
```
name: ${NAME}
namespace: ${NAMESPACE}
```
and not 
```
name: ${NAME}
name: ${NAMESPACE}
``` 

https://github.com/JFrogDev/artifactory-docker-examples/blob/470cbb63c47afe985e8423b425f6e1607d4f7524/openshift/artifactory/database/postgresql/secrets/postgresql-secret.yaml#L11

**Comment by elioengcomp** [comment]
Hi @0pen5pace,

Thank you for the catch! It has been fixed.

Best.
Elio
